site_name: Data Vis With Python
site_url: https://www.sdsc.edu
site_description: SDSC Tutorial.
site_author: SDSC Training

repo_url: https://github.com/sdsc-hpc-training-org/data_vis_with_python
edit_uri: ""

theme: amelia